server:
  port: 8083
  error:
    include-message: always
  servlet:
    context-path: /api
springdoc:
  swagger-ui:
    disable-swagger-default-url: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/kotlin-api?useSSL=false&serverTimezone=UTC
    username: app_user
    password: password
    initialization-mode: always
    driverClassName: org.postgresql.Driver
    hikari:
      schema: api
  jpa:
    properties:
      hibernate:
        default_schema: api
  flyway:
    baseline-on-migrate: true

keycloak:
  auth-server-url: http://localhost:8180/auth
  realm: Base
  resource: ApiClient
  public-client: true
  # session:
 #   jdbc:
 #     initialize-schema: always

flyway:
  url: jdbc:postgresql://localhost:5434/kotlin-api
  schemas: api
  user: app_user
  password: password
  baseline-on-migrate: true



