name: mvn install

on:
  pull_request:
    branches: [ '**' ]

jobs:
  app-mvn:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'
      - name: Run integration tests
        run: mvn install
